on: [workflow_call, push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ./
        with:
          who-to-greet: "Sam" # passing in to the input id an id
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
